package runtime

import (
	"bufio"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

const configTemplatePath = "config.example.toml"

const fallbackBootstrapConfig = `# Generated by helix-tui first-run bootstrap.
# You can replace this file with config.example.toml for all options.

mode = "manual"

[identity]
human_name = "Operator"
human_alias = ""
agent_name = "Helix"

[alpaca]
env = "paper"
feed = "iex"
api_key = ""
api_secret = ""
base_url = ""
data_url = ""

[keyring]
use = true
save = true
service = "helix-tui"
user = "alpaca"

[agent]
type = "heuristic"
watchlist = ["AAPL", "MSFT", "TSLA", "NVDA"]
interval = "15s"
sync_timeout = "15s"
order_timeout = "15s"
max_intents = 1
dry_run = true

[database]
path = "logs/helix.db"
`

func maybeBootstrapConfig(path string, explicit bool, input io.Reader, output io.Writer) error {
	// Only bootstrap for implicit/default config paths.
	if explicit {
		return nil
	}
	return maybeBootstrapConfigWithPrompt(path, input, output, isInteractiveInput(input))
}

func maybeBootstrapConfigWithPrompt(path string, input io.Reader, output io.Writer, interactive bool) error {
	path = strings.TrimSpace(path)
	if path == "" {
		return nil
	}
	if output == nil {
		output = io.Discard
	}

	_, err := os.Stat(path)
	if err == nil {
		return nil
	}
	if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("stat config %q: %w", path, err)
	}
	if !interactive {
		return nil
	}

	fmt.Fprintf(output, "config file %q was not found.\n", path)
	fmt.Fprint(output, "create it now? [Y/n]: ")
	answer, readErr := readPromptLine(input)
	if readErr != nil {
		return fmt.Errorf("read config bootstrap prompt: %w", readErr)
	}
	if isNegativeAnswer(answer) {
		fmt.Fprintln(output, "continuing without config file (runtime defaults will be used).")
		return nil
	}

	source, err := writeBootstrapConfig(path)
	if err != nil {
		return err
	}
	fmt.Fprintf(output, "created %q from %s.\n", path, source)
	return nil
}

func writeBootstrapConfig(path string) (string, error) {
	content, source, err := loadBootstrapTemplate()
	if err != nil {
		return "", err
	}
	dir := filepath.Dir(path)
	if dir != "." && dir != "" {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return "", fmt.Errorf("create config directory %q: %w", dir, err)
		}
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		return "", fmt.Errorf("write config %q: %w", path, err)
	}
	return source, nil
}

func loadBootstrapTemplate() ([]byte, string, error) {
	content, err := os.ReadFile(configTemplatePath)
	switch {
	case err == nil:
		trimmed := strings.TrimSpace(string(content))
		if trimmed == "" {
			return []byte(fallbackBootstrapConfig), "built-in fallback template", nil
		}
		return content, configTemplatePath, nil
	case errors.Is(err, os.ErrNotExist):
		return []byte(fallbackBootstrapConfig), "built-in fallback template", nil
	default:
		return nil, "", fmt.Errorf("read %q: %w", configTemplatePath, err)
	}
}

func isInteractiveInput(input io.Reader) bool {
	f, ok := input.(*os.File)
	if !ok {
		return false
	}
	info, err := f.Stat()
	if err != nil {
		return false
	}
	return (info.Mode() & os.ModeCharDevice) != 0
}

func isNegativeAnswer(answer string) bool {
	switch strings.ToLower(strings.TrimSpace(answer)) {
	case "n", "no":
		return true
	default:
		return false
	}
}

func readPromptLine(input io.Reader) (string, error) {
	if input == nil {
		return "", nil
	}
	reader := bufio.NewReader(input)
	line, err := reader.ReadString('\n')
	if err != nil && !errors.Is(err, io.EOF) {
		return "", err
	}
	return line, nil
}
